### ISSUE TITLE
Handle arrow keys

### ISSUE THREAD

**Issue by MaanooAk** [MaanooAk/yoda#8]
If you press one of the arrow keys:

![screenshot from 2017-01-27 13-33-31](https://cloud.githubusercontent.com/assets/6997990/22369588/78a46c6e-e495-11e6-9123-02d8020338e8.png)

They should at least do nothing

**Comment by evaperon** [comment]
command history? how do I implement this?

**Comment by MaanooAk** [comment]
We should use "GNU Readline" if we can.

**Comment by MaanooAk** [comment]
The compiler now can handle the GNU readline, also the `readline6-dev` package (which is needed) is now auto installed the first time you call `make`.
